export const initFiltersValue = {
  minBlurValue: 0,
  maxBlurValue: 100,
  minBrightnessValue: -0.5,
  maxBrightnessValue: 0.5,
  minContrastValue: -20,
  maxContrastValue: 20,
  minHueRotateValue: -180,
  maxHueRotateValue: 180,
  minOpacityValue: 0,
  maxOpacityValue: 1,
  minNoiseValue: 0,
  maxNoiseValue: 0.5,
  minPixelateValue: 1,
  maxPixelateValue: 100,
};
